apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cast-service-chart.fullname" . }}
  labels:
    {{- include "cast-service-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cast-service-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cast-service-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
