apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: movie-db
  name: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: movie-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: movie-db
    spec:
      containers:
      - env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRES_USER
        image: postgres:12.1-alpine
        imagePullPolicy: ""
        name: movie-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data-movie
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postgres-data-movie
        persistentVolumeClaim:
          claimName: postgres-data-movie
status: {}
