apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: {{ include "app.name" . }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresDb | b64enc | quote }}