replicaCount: 1

image:
  repository: kilann31/exam_jenkins
  tag: movie-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

postgres:
  image: postgres:12.1-alpine
  user: ""
  password: ""
  db: ""
  servicePort: 5432

env:
  - name: DATABASE_URI
    value: postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@app-movie-service-chart-postgres:5432/{{ .Values.postgres.db }}
  - name: CAST_SERVICE_HOST_URL
    value: "http://cast-service:8000/api/v1/casts/"

resources: {}
