replicaCount: 1

image:
  repository: kilann31/exam_jenkins
  tag: movie-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  - name: DATABASE_URI
    value: {{ .Values.env.CAST_SERVICE_HOST_URL }}
  - name: CAST_SERVICE_HOST_URL
    value: "http://cast-service:8000/api/v1/casts/"

resources: {}
