replicaCount: 1

image:
  repository: kilann31/exam_jenkins
  tag: movie-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

postgres:
  image: postgres:12.1-alpine
  user: {{ postgresUser }}
  password: {{ postgresPassword }}
  db: {{ postgresDb }}
  servicePort: 5432

env:
  - name: DATABASE_URI
    value: postgresql://{{ postgresUser }}:{{ postgresPassword }}@app-movie-service-chart-postgres:5432/{{ postgresDb }}
  - name: CAST_SERVICE_HOST_URL
    value: "http://cast-service:8000/api/v1/casts/"

resources: {}
