replicaCount: 1

image:
  repository: kilann31/exam_jenkins
  tag: movie-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

postgres:
  image: postgres:12.1-alpine
  user: your_postgres_user
  password: your_postgres_password
  db: your_postgres_db
  servicePort: 5432

env:
  - name: DATABASE_URI
    value: postgresql://{{ .Values.postgresUser }}:{{ .Values.postgresPassword }}@movie-db-service:5432/{{ .Values.postgresDb }}
  - name: CAST_SERVICE_HOST_URL
    value: "http://cast-service:8000/api/v1/casts/"

resources: {}
