replicaCount: 1

image:
  repository: kilann31/exam_jenkins
  tag: cast-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  - name: DATABASE_URI
    value: postgresql://{{ postgresUser }}:{{ postgresPassword }}@movie-db-service:5432/{{ moviePostgresDb }}

resources: {}
