apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-service-chart.fullname" . }}
  labels:
    {{- include "movie-service-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "movie-service-chart.name" . }}
